# Copyright 2025 The Focus Authors
# You can use, redistribute, and/or modify this source code under
# the terms of the GPL-3.0 license that can be found in the LICENSE file.

component("focus_services") {
  sources = [
    "focus_services_helpers.cc",
    "focus_services_helpers.h",
    "pref_names.h",
    "schema.cc",
    "schema.h",
  ]

  public_deps = [
    "//base",
    "//components/prefs",
    "//url",
    "//net",
  ]

  defines = [ "IS_FOCUS_IMPL" ]
}
