# Copyright (c) 2023 The Brave Authors. All rights reserved.
# Copyright (c) 2026 Focus Browser contributors.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

static_library("resolver") {
  sources = [
    "domain_resolver.cc",
    "domain_resolver.h",
  ]

  visibility = [ "//components/focus_block/*" ]

  deps = [
    "//components/focus_block/rs:rust_lib",
    "//net",
  ]
}
