// Generated by components/focus_onboarding/util/generate-i18n.mts.
// Do not edit manually.

import russianStrings from './strings.ru.json';
import { isRussianUiLocale } from './locale';

type StringKey = never
 | "pageTitle"
 | "setupCaption"
 | "setupStepsAria"
 | "setupNote"
 | "setupStepFocus"
 | "setupStepAppearance"
 | "setupStepSearch"
 | "setupStepImport"
 | "setupStepPasswords"
 | "setupStepDefault"
 | "setupStepShortcuts"
 | "buttonUseDefaults"
 | "buttonConfigure"
 | "buttonNext"
 | "buttonBack"
 | "buttonLetsGo"
 | "buttonSkip"
 | "buttonStart"
 | "navigationError"
 | "navigationStep"
 | "navigationOf"
 | "partnerTitle"
 | "partnerTooltip"
 | "welcomeGreeting"
 | "welcomeBody"
 | "welcomeEyebrow"
 | "welcomeFeaturesLabel"
 | "welcomeFeatureQuiet"
 | "welcomeFeatureClean"
 | "welcomeFeatureIntent"
 | "welcomeTermsNote"
 | "welcomeTermsPrivacy"
 | "welcomeTermsAnd"
 | "welcomeTermsUse"
 | "welcomeFooter"
 | "focusTitle"
 | "focusSubtitle"
 | "focusQuietTitle"
 | "focusQuietDesc"
 | "focusMinimalTitle"
 | "focusMinimalDesc"
 | "focusMotionTitle"
 | "focusMotionDesc"
 | "focusNote"
 | "appearanceTitle"
 | "appearanceSubtitle"
 | "appearanceBarTitle"
 | "appearanceBarFull"
 | "appearanceBarFullDesc"
 | "appearanceBarCentered"
 | "appearanceBarCenteredDesc"
 | "appearanceBarMinimal"
 | "appearanceBarMinimalDesc"
 | "appearanceNote"
 | "shortcutsTitle"
 | "shortcutsSubtitle"
 | "shortcutsSocial"
 | "shortcutsCoding"
 | "shortcutsAi"
 | "shortcutsProductivity"
 | "shortcutsEmpty"
 | "shortcutsSelected"
 | "shortcutsLimit"
 | "finishTitle"
 | "finishBody"
 | "searchTitle"
 | "searchSubtitle"
 | "searchLoading"
 | "searchNone"
 | "searchError"
 | "searchCategoriesPrivate"
 | "searchCategoriesSmall"
 | "searchCategoriesMainstream"
 | "searchCategoriesCustom"
 | "searchEnginesDuckduckgo"
 | "searchEnginesKagi"
 | "searchEnginesQwant"
 | "searchEnginesEcosia"
 | "searchEnginesBing"
 | "searchEnginesGoogle"
 | "defaultBrowserTitle"
 | "defaultBrowserSubtitle"
 | "defaultBrowserYes"
 | "defaultBrowserNo"
 | "defaultBrowserYesDesc"
 | "defaultBrowserNoDesc"
 | "dataImportTitle"
 | "dataImportSubtitle"
 | "dataImportSubtitleNoChrome"
 | "dataImportBookmarks"
 | "dataImportHistory"
 | "dataImportExtensions"
 | "dataImportPasswords"
 | "dataImportAutofill"
 | "dataImportSearchEngine"
 | "dataImportLoading"
 | "dataImportNone"
 | "dataImportLoadError"
 | "dataImportImported"
 | "dataImportDefaultProfile"
 | "dataImportChromeQuickTitle"
 | "dataImportChromeQuickDesc"
 | "dataImportChromeQuickButton"
 | "dataImportChromeQuickWorking"
 | "dataImportChromeQuickDone"
 | "dataImportChromeQuickFailed"
 | "dataImportChromeQuickRetry"
 | "passwordTitle"
 | "passwordSubtitle"
 | "passwordLocalTitle"
 | "passwordLocalDesc"
 | "passwordFillTitle"
 | "passwordFillDesc"
 | "passwordPasskeysTitle"
 | "passwordPasskeysDesc"
 | "passwordOpenManager"
 | "passwordOpenImport"
 | "passwordNote"
 | "passwordImportGuide"
 | "passwordSetupGuide"
 | "passwordPrivacy"
 | "passwordInstall"
 | "passwordInstalled"
 | "passwordError"
 | "passwordManagersProtonPass"
 | "passwordManagersBitwarden"
 | "passwordManagersOnePassword"
 | "passwordManagersDashlane"
 | "passwordManagersIcloudPasswords"
 | "passwordManagersKeePassXc";

type LoadTimeData = {
    data?: Record<string, string>;
    getString(key: string): string;
};

declare global {
    var loadTimeData: LoadTimeData | undefined;
}

let loadTimeData: LoadTimeData | undefined;
const installLoadTimeData = (): LoadTimeData => {
    if (globalThis.loadTimeData) {
        return globalThis.loadTimeData;
    }

    globalThis.loadTimeData = {
        data: {},
        getString(key: string) {
            return globalThis.loadTimeData?.data?.[key] ?? '';
        },
    };
    return globalThis.loadTimeData;
};

let chromiumStringsPromise: Promise<void> | undefined;
const loadChromiumStrings = async (): Promise<void> => {
    chromiumStringsPromise ??= new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = '/strings.js';
        script.onload = () => resolve();
        script.onerror = () => reject(new Error('failed to load /strings.js'));
        document.head.append(script);
    });

    await chromiumStringsPromise;
};

export const initStrings = async (): Promise<void> => {
    if (loadTimeData) {
        return;
    }

    if (globalThis.location.protocol !== 'chrome:') {
        return;
    }

    loadTimeData = installLoadTimeData();
    await loadChromiumStrings();
};

const ENGLISH_STRINGS = ({    "pageTitle": "Focus Browser Setup",
    "setupCaption": "Initial setup",
    "setupStepsAria": "Initial setup steps",
    "setupNote": "You can change every option later in browser settings.",
    "setupStepFocus": "Work preferences",
    "setupStepAppearance": "Address bar",
    "setupStepSearch": "Search",
    "setupStepImport": "Data import",
    "setupStepPasswords": "Passwords",
    "setupStepDefault": "Default browser",
    "setupStepShortcuts": "Shortcuts",
    "buttonUseDefaults": "Use focus preset",
    "buttonConfigure": "Set up Focus Browser",
    "buttonNext": "Next",
    "buttonBack": "Back",
    "buttonLetsGo": "Start working",
    "buttonSkip": "Skip",
    "buttonStart": "Start",
    "navigationError": "Couldn't save your settings. Check your choices and try again.",
    "navigationStep": "Step",
    "navigationOf": "of",
    "partnerTitle": "Focus Browser partner",
    "partnerTooltip": "Payment from this service helps support Focus Browser development.",
    "welcomeGreeting": "Focus on what matters.",
    "welcomeBody": "Focus Browser removes distractions from the interface, so your attention stays on the task at hand.",
    "welcomeEyebrow": "Focus Browser · built for focused work",
    "welcomeFeaturesLabel": "Focus Browser benefits",
    "welcomeFeatureQuiet": "Fewer distractions",
    "welcomeFeatureClean": "Clean interface",
    "welcomeFeatureIntent": "Built for deep work",
    "welcomeTermsNote": "By continuing, you accept the",
    "welcomeTermsPrivacy": "privacy policy",
    "welcomeTermsAnd": "and",
    "welcomeTermsUse": "terms of use",
    "welcomeFooter": "You can change every selected option later in settings.",
    "focusTitle": "Set up your work preferences",
    "focusSubtitle": "Choose a calm interface with fewer distractions. You can change these options later.",
    "focusQuietTitle": "Quiet notifications",
    "focusQuietDesc": "Stop websites from interrupting you with notification requests.",
    "focusMinimalTitle": "Minimal interface",
    "focusMinimalDesc": "Hides the Home button and bookmarks bar. Your bookmarks remain available in the menu.",
    "focusMotionTitle": "Smooth animations",
    "focusMotionDesc": "Adds calm, fluid transitions. The system reduced-motion setting always takes priority.",
    "focusNote": "You can change every selected option later in browser settings.",
    "appearanceTitle": "Set up the address bar",
    "appearanceSubtitle": "Choose a comfortable width for entering addresses and search queries.",
    "appearanceBarTitle": "Address bar style",
    "appearanceBarFull": "Full width",
    "appearanceBarFullDesc": "Maximum room for long addresses.",
    "appearanceBarCentered": "Centered",
    "appearanceBarCenteredDesc": "A balanced layout for everyday work.",
    "appearanceBarMinimal": "Minimal",
    "appearanceBarMinimalDesc": "A compact field with minimal visual noise.",
    "appearanceNote": "You can change these options later under Settings → Appearance.",
    "shortcutsTitle": "What should stay close at hand?",
    "shortcutsSubtitle": "Choose shortcuts for the New Tab page. Nothing is selected by default.",
    "shortcutsSocial": "Social media",
    "shortcutsCoding": "Coding",
    "shortcutsAi": "AI",
    "shortcutsProductivity": "Work and productivity",
    "shortcutsEmpty": "No shortcuts are selected. You can skip this step.",
    "shortcutsSelected": "Selected:",
    "shortcutsLimit": "You can select up to 10 shortcuts.",
    "finishTitle": "You're ready to work",
    "finishBody": "Focus Browser is set up. Open a task and focus on what matters.",
    "searchTitle": "Search engine",
    "searchSubtitle": "Choose your default search engine. You can change it later in settings.",
    "searchLoading": "Loading available search engines…",
    "searchNone": "No available search engines were found.",
    "searchError": "Couldn't load the search engine list. You can continue with the current engine.",
    "searchCategoriesPrivate": "Privacy-first search without advertising profiles.",
    "searchCategoriesSmall": "A more transparent alternative to the major search engines.",
    "searchCategoriesMainstream": "A popular search engine that may collect data for personalization.",
    "searchCategoriesCustom": "A custom search engine. Focus Browser hasn't reviewed its privacy policy.",
    "searchEnginesDuckduckgo": "Privacy-focused. Uses Bing results and doesn't create an advertising profile.",
    "searchEnginesKagi": "Search without ads or tracking and with customizable results. A paid account is required.",
    "searchEnginesQwant": "A European search engine powered by Bing results.",
    "searchEnginesEcosia": "Directs part of its advertising revenue to environmental projects. Uses Bing and Google results.",
    "searchEnginesBing": "Microsoft's popular search engine, with personalized results and ads.",
    "searchEnginesGoogle": "Google's popular search engine, with personalized results and ads.",
    "defaultBrowserTitle": "Make Focus Browser your default?",
    "defaultBrowserSubtitle": "Links from other apps will open in Focus Browser. You can change this choice in Windows.",
    "defaultBrowserYes": "Yes, make it default",
    "defaultBrowserNo": "Not now",
    "defaultBrowserYesDesc": "Open web links in Focus Browser.",
    "defaultBrowserNoDesc": "Keep your current default browser.",
    "dataImportTitle": "Bring your data from another browser",
    "dataImportSubtitle": "Choose a profile or import supported data from Google Chrome with one click.",
    "dataImportSubtitleNoChrome": "Choose a detected browser and the data you want to bring over.",
    "dataImportBookmarks": "Bookmarks",
    "dataImportHistory": "History",
    "dataImportExtensions": "Extensions",
    "dataImportPasswords": "Passwords",
    "dataImportAutofill": "Autofill",
    "dataImportSearchEngine": "Search engine",
    "dataImportLoading": "Looking for installed browsers…",
    "dataImportNone": "No profiles are available to import. You can continue without importing.",
    "dataImportLoadError": "Couldn't load the browser list. You can continue without importing.",
    "dataImportImported": "Already imported",
    "dataImportDefaultProfile": "Default profile",
    "dataImportChromeQuickTitle": "Import supported data from Google Chrome",
    "dataImportChromeQuickDesc": "Available bookmarks, history, and extensions.",
    "dataImportChromeQuickButton": "Import",
    "dataImportChromeQuickWorking": "Importing…",
    "dataImportChromeQuickDone": "Done",
    "dataImportChromeQuickFailed": "Couldn't import the data. Try again or choose a profile below.",
    "dataImportChromeQuickRetry": "Try again",
    "passwordTitle": "Focus Password Manager",
    "passwordSubtitle": "Built into the browser and enabled by default. There's nothing else to install.",
    "passwordLocalTitle": "Protected local storage",
    "passwordLocalDesc": "Passwords are encrypted by Windows and stored in your Focus Browser profile.",
    "passwordFillTitle": "Autofill and generation",
    "passwordFillDesc": "Focus Browser saves, fills, and creates strong passwords directly on websites.",
    "passwordPasskeysTitle": "Passwords and passkeys",
    "passwordPasskeysDesc": "Manage saved sign-in details and supported passkeys in one place.",
    "passwordOpenManager": "Open manager",
    "passwordOpenImport": "Import passwords",
    "passwordNote": "Chrome passwords are not included in browser data import. Export them from Chrome, then use Import passwords above.",
    "passwordImportGuide": "Import",
    "passwordSetupGuide": "Setup",
    "passwordPrivacy": "Privacy",
    "passwordInstall": "Install",
    "passwordInstalled": "Installed",
    "passwordError": "Error:",
    "passwordManagersProtonPass": "Proton's open-source password manager with a free plan.",
    "passwordManagersBitwarden": "A popular open-source password manager with a free plan and self-hosting support.",
    "passwordManagersOnePassword": "A paid, closed-source password manager.",
    "passwordManagersDashlane": "A paid, closed-source password manager with data storage in Europe.",
    "passwordManagersIcloudPasswords": "Apple's free password manager. On Windows it may require signing in again after a browser restart.",
    "passwordManagersKeePassXc": "A local, free, open-source password manager for advanced users.",});

export const getUiLocale = (): string => {
    const applicationLocale =
        (loadTimeData ?? globalThis.loadTimeData)?.getString('applicationLocale');
    return globalThis.navigator?.language || applicationLocale || 'en-US';
};

const getString = (key: StringKey): string => {
    if (isRussianUiLocale(getUiLocale())) {
        const russian = (russianStrings as Record<StringKey, string>)[key];
        if (russian) {
            return russian;
        }
    }

    const english = (ENGLISH_STRINGS as Record<StringKey, string>)[key];
    if (!english) {
        console.error(`Could not get string for ${key}`);
        return `¡${key}!`;
    }

    return english;
};

export const s = {
    page: {
        get title() { return getString('pageTitle'); },
    },
    setup: {
        get caption() { return getString('setupCaption'); },
        get stepsAria() { return getString('setupStepsAria'); },
        get note() { return getString('setupNote'); },
        get stepFocus() { return getString('setupStepFocus'); },
        get stepAppearance() { return getString('setupStepAppearance'); },
        get stepSearch() { return getString('setupStepSearch'); },
        get stepImport() { return getString('setupStepImport'); },
        get stepPasswords() { return getString('setupStepPasswords'); },
        get stepDefault() { return getString('setupStepDefault'); },
        get stepShortcuts() { return getString('setupStepShortcuts'); },
    },
    button: {
        get useDefaults() { return getString('buttonUseDefaults'); },
        get configure() { return getString('buttonConfigure'); },
        get next() { return getString('buttonNext'); },
        get back() { return getString('buttonBack'); },
        get letsGo() { return getString('buttonLetsGo'); },
        get skip() { return getString('buttonSkip'); },
        get start() { return getString('buttonStart'); },
    },
    navigation: {
        get error() { return getString('navigationError'); },
        get step() { return getString('navigationStep'); },
        get of() { return getString('navigationOf'); },
    },
    partner: {
        get title() { return getString('partnerTitle'); },
        get tooltip() { return getString('partnerTooltip'); },
    },
    welcome: {
        get greeting() { return getString('welcomeGreeting'); },
        get body() { return getString('welcomeBody'); },
        get eyebrow() { return getString('welcomeEyebrow'); },
        get featuresLabel() { return getString('welcomeFeaturesLabel'); },
        get featureQuiet() { return getString('welcomeFeatureQuiet'); },
        get featureClean() { return getString('welcomeFeatureClean'); },
        get featureIntent() { return getString('welcomeFeatureIntent'); },
        get termsNote() { return getString('welcomeTermsNote'); },
        get termsPrivacy() { return getString('welcomeTermsPrivacy'); },
        get termsAnd() { return getString('welcomeTermsAnd'); },
        get termsUse() { return getString('welcomeTermsUse'); },
        get footer() { return getString('welcomeFooter'); },
    },
    focus: {
        get title() { return getString('focusTitle'); },
        get subtitle() { return getString('focusSubtitle'); },
        get quietTitle() { return getString('focusQuietTitle'); },
        get quietDesc() { return getString('focusQuietDesc'); },
        get minimalTitle() { return getString('focusMinimalTitle'); },
        get minimalDesc() { return getString('focusMinimalDesc'); },
        get motionTitle() { return getString('focusMotionTitle'); },
        get motionDesc() { return getString('focusMotionDesc'); },
        get note() { return getString('focusNote'); },
    },
    appearance: {
        get title() { return getString('appearanceTitle'); },
        get subtitle() { return getString('appearanceSubtitle'); },
        get barTitle() { return getString('appearanceBarTitle'); },
        get barFull() { return getString('appearanceBarFull'); },
        get barFullDesc() { return getString('appearanceBarFullDesc'); },
        get barCentered() { return getString('appearanceBarCentered'); },
        get barCenteredDesc() { return getString('appearanceBarCenteredDesc'); },
        get barMinimal() { return getString('appearanceBarMinimal'); },
        get barMinimalDesc() { return getString('appearanceBarMinimalDesc'); },
        get note() { return getString('appearanceNote'); },
    },
    shortcuts: {
        get title() { return getString('shortcutsTitle'); },
        get subtitle() { return getString('shortcutsSubtitle'); },
        get social() { return getString('shortcutsSocial'); },
        get coding() { return getString('shortcutsCoding'); },
        get ai() { return getString('shortcutsAi'); },
        get productivity() { return getString('shortcutsProductivity'); },
        get empty() { return getString('shortcutsEmpty'); },
        get selected() { return getString('shortcutsSelected'); },
        get limit() { return getString('shortcutsLimit'); },
    },
    finish: {
        get title() { return getString('finishTitle'); },
        get body() { return getString('finishBody'); },
    },
    search: {
        get title() { return getString('searchTitle'); },
        get subtitle() { return getString('searchSubtitle'); },
        get loading() { return getString('searchLoading'); },
        get none() { return getString('searchNone'); },
        get error() { return getString('searchError'); },
    },
    searchCategories: {
        get private() { return getString('searchCategoriesPrivate'); },
        get small() { return getString('searchCategoriesSmall'); },
        get mainstream() { return getString('searchCategoriesMainstream'); },
        get custom() { return getString('searchCategoriesCustom'); },
    },
    searchEngines: {
        get duckduckgo() { return getString('searchEnginesDuckduckgo'); },
        get kagi() { return getString('searchEnginesKagi'); },
        get qwant() { return getString('searchEnginesQwant'); },
        get ecosia() { return getString('searchEnginesEcosia'); },
        get bing() { return getString('searchEnginesBing'); },
        get google() { return getString('searchEnginesGoogle'); },
    },
    defaultBrowser: {
        get title() { return getString('defaultBrowserTitle'); },
        get subtitle() { return getString('defaultBrowserSubtitle'); },
        get yes() { return getString('defaultBrowserYes'); },
        get no() { return getString('defaultBrowserNo'); },
        get yesDesc() { return getString('defaultBrowserYesDesc'); },
        get noDesc() { return getString('defaultBrowserNoDesc'); },
    },
    dataImport: {
        get title() { return getString('dataImportTitle'); },
        get subtitle() { return getString('dataImportSubtitle'); },
        get subtitleNoChrome() { return getString('dataImportSubtitleNoChrome'); },
        get bookmarks() { return getString('dataImportBookmarks'); },
        get history() { return getString('dataImportHistory'); },
        get extensions() { return getString('dataImportExtensions'); },
        get passwords() { return getString('dataImportPasswords'); },
        get autofill() { return getString('dataImportAutofill'); },
        get searchEngine() { return getString('dataImportSearchEngine'); },
        get loading() { return getString('dataImportLoading'); },
        get none() { return getString('dataImportNone'); },
        get loadError() { return getString('dataImportLoadError'); },
        get imported() { return getString('dataImportImported'); },
        get defaultProfile() { return getString('dataImportDefaultProfile'); },
        get chromeQuickTitle() { return getString('dataImportChromeQuickTitle'); },
        get chromeQuickDesc() { return getString('dataImportChromeQuickDesc'); },
        get chromeQuickButton() { return getString('dataImportChromeQuickButton'); },
        get chromeQuickWorking() { return getString('dataImportChromeQuickWorking'); },
        get chromeQuickDone() { return getString('dataImportChromeQuickDone'); },
        get chromeQuickFailed() { return getString('dataImportChromeQuickFailed'); },
        get chromeQuickRetry() { return getString('dataImportChromeQuickRetry'); },
    },
    password: {
        get title() { return getString('passwordTitle'); },
        get subtitle() { return getString('passwordSubtitle'); },
        get localTitle() { return getString('passwordLocalTitle'); },
        get localDesc() { return getString('passwordLocalDesc'); },
        get fillTitle() { return getString('passwordFillTitle'); },
        get fillDesc() { return getString('passwordFillDesc'); },
        get passkeysTitle() { return getString('passwordPasskeysTitle'); },
        get passkeysDesc() { return getString('passwordPasskeysDesc'); },
        get openManager() { return getString('passwordOpenManager'); },
        get openImport() { return getString('passwordOpenImport'); },
        get note() { return getString('passwordNote'); },
        get importGuide() { return getString('passwordImportGuide'); },
        get setupGuide() { return getString('passwordSetupGuide'); },
        get privacy() { return getString('passwordPrivacy'); },
        get install() { return getString('passwordInstall'); },
        get installed() { return getString('passwordInstalled'); },
        get error() { return getString('passwordError'); },
    },
    passwordManagers: {
        get protonPass() { return getString('passwordManagersProtonPass'); },
        get bitwarden() { return getString('passwordManagersBitwarden'); },
        get onePassword() { return getString('passwordManagersOnePassword'); },
        get dashlane() { return getString('passwordManagersDashlane'); },
        get icloudPasswords() { return getString('passwordManagersIcloudPasswords'); },
        get keePassXc() { return getString('passwordManagersKeePassXc'); },
    },
} as const;
