// Generated by components/focus_onboarding/util/generate-i18n.mts.
// Do not edit manually.

type StringKey = never
 | "pageTitle"
 | "setupCaption"
 | "setupStepsAria"
 | "setupNote"
 | "setupStepFocus"
 | "setupStepAppearance"
 | "setupStepSearch"
 | "setupStepImport"
 | "setupStepPasswords"
 | "setupStepDefault"
 | "setupStepShortcuts"
 | "buttonUseDefaults"
 | "buttonConfigure"
 | "buttonNext"
 | "buttonBack"
 | "buttonLetsGo"
 | "buttonSkip"
 | "buttonStart"
 | "navigationError"
 | "partnerTitle"
 | "partnerTooltip"
 | "welcomeGreeting"
 | "welcomeBody"
 | "welcomeEyebrow"
 | "welcomeFeaturesLabel"
 | "welcomeFeatureQuiet"
 | "welcomeFeatureClean"
 | "welcomeFeatureIntent"
 | "welcomeTermsNote"
 | "welcomeTermsPrivacy"
 | "welcomeTermsAnd"
 | "welcomeTermsUse"
 | "welcomeFooter"
 | "focusTitle"
 | "focusSubtitle"
 | "focusQuietTitle"
 | "focusQuietDesc"
 | "focusMinimalTitle"
 | "focusMinimalDesc"
 | "focusMotionTitle"
 | "focusMotionDesc"
 | "focusNote"
 | "appearanceTitle"
 | "appearanceSubtitle"
 | "appearanceBarTitle"
 | "appearanceBarFull"
 | "appearanceBarFullDesc"
 | "appearanceBarCentered"
 | "appearanceBarCenteredDesc"
 | "appearanceBarMinimal"
 | "appearanceBarMinimalDesc"
 | "appearanceNote"
 | "shortcutsTitle"
 | "shortcutsSubtitle"
 | "shortcutsSocial"
 | "shortcutsCoding"
 | "shortcutsAi"
 | "shortcutsProductivity"
 | "shortcutsEmpty"
 | "shortcutsSelected"
 | "shortcutsLimit"
 | "finishTitle"
 | "finishBody"
 | "searchTitle"
 | "searchSubtitle"
 | "searchLoading"
 | "searchNone"
 | "searchError"
 | "searchCategoriesPrivate"
 | "searchCategoriesSmall"
 | "searchCategoriesMainstream"
 | "searchCategoriesCustom"
 | "searchEnginesDuckduckgo"
 | "searchEnginesKagi"
 | "searchEnginesQwant"
 | "searchEnginesEcosia"
 | "searchEnginesBing"
 | "searchEnginesGoogle"
 | "defaultBrowserTitle"
 | "defaultBrowserSubtitle"
 | "defaultBrowserYes"
 | "defaultBrowserNo"
 | "defaultBrowserYesDesc"
 | "defaultBrowserNoDesc"
 | "dataImportTitle"
 | "dataImportSubtitle"
 | "dataImportSubtitleNoChrome"
 | "dataImportBookmarks"
 | "dataImportHistory"
 | "dataImportExtensions"
 | "dataImportPasswords"
 | "dataImportAutofill"
 | "dataImportSearchEngine"
 | "dataImportLoading"
 | "dataImportNone"
 | "dataImportLoadError"
 | "dataImportImported"
 | "dataImportDefaultProfile"
 | "dataImportChromeQuickTitle"
 | "dataImportChromeQuickDesc"
 | "dataImportChromeQuickButton"
 | "dataImportChromeQuickWorking"
 | "dataImportChromeQuickDone"
 | "dataImportChromeQuickFailed"
 | "dataImportChromeQuickRetry"
 | "passwordTitle"
 | "passwordSubtitle"
 | "passwordLocalTitle"
 | "passwordLocalDesc"
 | "passwordFillTitle"
 | "passwordFillDesc"
 | "passwordPasskeysTitle"
 | "passwordPasskeysDesc"
 | "passwordOpenManager"
 | "passwordOpenImport"
 | "passwordNote"
 | "passwordImportGuide"
 | "passwordSetupGuide"
 | "passwordPrivacy"
 | "passwordInstall"
 | "passwordInstalled"
 | "passwordError"
 | "passwordManagersProtonPass"
 | "passwordManagersBitwarden"
 | "passwordManagersOnePassword"
 | "passwordManagersDashlane"
 | "passwordManagersIcloudPasswords"
 | "passwordManagersKeePassXc";

type LoadTimeData = {
    data?: Record<string, string>;
    getString(key: string): string;
};

declare global {
    var loadTimeData: LoadTimeData | undefined;
}

let loadTimeData: LoadTimeData | undefined;
const installLoadTimeData = (): LoadTimeData => {
    if (globalThis.loadTimeData) {
        return globalThis.loadTimeData;
    }

    globalThis.loadTimeData = {
        data: {},
        getString(key: string) {
            return globalThis.loadTimeData?.data?.[key] ?? '';
        },
    };
    return globalThis.loadTimeData;
};

let chromiumStringsPromise: Promise<void> | undefined;
const loadChromiumStrings = async (): Promise<void> => {
    chromiumStringsPromise ??= new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = '/strings.js';
        script.onload = () => resolve();
        script.onerror = () => reject(new Error('failed to load /strings.js'));
        document.head.append(script);
    });

    await chromiumStringsPromise;
};

export const initStrings = async (): Promise<void> => {
    if (loadTimeData) {
        return;
    }

    if (globalThis.location.protocol !== 'chrome:') {
        return;
    }

    loadTimeData = installLoadTimeData();
    await loadChromiumStrings();
};

const DEV_STRINGS = import.meta.env.DEV ? ({    "pageTitle": "Настройка Focus Browser",
    "setupCaption": "Первоначальная настройка",
    "setupStepsAria": "Этапы первоначальной настройки",
    "setupNote": "Все параметры можно изменить позже в настройках браузера.",
    "setupStepFocus": "Режим работы",
    "setupStepAppearance": "Адресная строка",
    "setupStepSearch": "Поиск",
    "setupStepImport": "Импорт данных",
    "setupStepPasswords": "Пароли",
    "setupStepDefault": "Основной браузер",
    "setupStepShortcuts": "Ярлыки",
    "buttonUseDefaults": "Применить готовые настройки",
    "buttonConfigure": "Настроить браузер",
    "buttonNext": "Далее",
    "buttonBack": "Назад",
    "buttonLetsGo": "Начать работу",
    "buttonSkip": "Пропустить",
    "buttonStart": "Начать",
    "navigationError": "Не удалось сохранить настройки. Проверьте выбор и попробуйте ещё раз.",
    "partnerTitle": "Партнёр Focus Browser",
    "partnerTooltip": "Оплата этого сервиса помогает развитию Focus Browser.",
    "welcomeGreeting": "Сосредоточьтесь на главном.",
    "welcomeBody": "Focus Browser убирает лишнее из интерфейса, чтобы внимание оставалось на текущей задаче.",
    "welcomeEyebrow": "Focus Browser · для сосредоточенной работы",
    "welcomeFeaturesLabel": "Преимущества Focus Browser",
    "welcomeFeatureQuiet": "Меньше отвлечений",
    "welcomeFeatureClean": "Чистый интерфейс",
    "welcomeFeatureIntent": "Создан для глубокой работы",
    "welcomeTermsNote": "Продолжая, вы принимаете",
    "welcomeTermsPrivacy": "политику конфиденциальности",
    "welcomeTermsAnd": "и",
    "welcomeTermsUse": "условия использования",
    "welcomeFooter": "Все выбранные параметры можно изменить позже в настройках.",
    "focusTitle": "Настройте режим работы",
    "focusSubtitle": "Выберите спокойный интерфейс без лишних отвлечений. Эти параметры можно изменить позже.",
    "focusQuietTitle": "Тихие уведомления",
    "focusQuietDesc": "Сайты не смогут отвлекать вас запросами на отправку уведомлений.",
    "focusMinimalTitle": "Минимальный интерфейс",
    "focusMinimalDesc": "Скрывает кнопку «Главная» и панель закладок. Закладки останутся доступны в меню.",
    "focusMotionTitle": "Плавные анимации",
    "focusMotionDesc": "Добавляет спокойные плавные переходы. Системная настройка уменьшения движения всегда имеет приоритет.",
    "focusNote": "Все выбранные параметры можно изменить позже в настройках браузера.",
    "appearanceTitle": "Настройте адресную строку",
    "appearanceSubtitle": "Выберите удобную ширину поля, в котором вводятся адреса и поисковые запросы.",
    "appearanceBarTitle": "Вид адресной строки",
    "appearanceBarFull": "Во всю ширину",
    "appearanceBarFullDesc": "Максимум места для длинных адресов.",
    "appearanceBarCentered": "По центру",
    "appearanceBarCenteredDesc": "Сбалансированный вид для повседневной работы.",
    "appearanceBarMinimal": "Минимальная",
    "appearanceBarMinimalDesc": "Компактное поле с минимумом визуального шума.",
    "appearanceNote": "Позже эти параметры можно изменить в разделе «Настройки → Внешний вид».",
    "shortcutsTitle": "Что оставить под рукой?",
    "shortcutsSubtitle": "Выберите ярлыки для новой вкладки. По умолчанию ничего не выбрано.",
    "shortcutsSocial": "Социальные сети",
    "shortcutsCoding": "Разработка",
    "shortcutsAi": "ИИ",
    "shortcutsProductivity": "Работа и продуктивность",
    "shortcutsEmpty": "Ярлыки не выбраны. Можно пропустить этот шаг.",
    "shortcutsSelected": "Выбрано:",
    "shortcutsLimit": "Можно выбрать не больше 10 ярлыков.",
    "finishTitle": "Всё готово для работы",
    "finishBody": "Focus Browser настроен. Откройте задачу и сосредоточьтесь на главном.",
    "searchTitle": "Поисковая система",
    "searchSubtitle": "Выберите поиск по умолчанию. Позже его можно сменить в настройках.",
    "searchLoading": "Загружаем доступные поисковые системы…",
    "searchNone": "Доступные поисковые системы не найдены.",
    "searchError": "Не удалось загрузить список поисковых систем. Можно продолжить с текущей.",
    "searchCategoriesPrivate": "Поиск с упором на конфиденциальность и без рекламного профилирования.",
    "searchCategoriesSmall": "Более прозрачная альтернатива крупным поисковым системам.",
    "searchCategoriesMainstream": "Популярная поисковая система, которая может собирать данные для персонализации.",
    "searchCategoriesCustom": "Пользовательская поисковая система. Focus Browser не проверял её политику конфиденциальности.",
    "searchEnginesDuckduckgo": "Ориентирован на конфиденциальность. Использует результаты Bing и не создаёт рекламный профиль пользователя.",
    "searchEnginesKagi": "Поиск без рекламы и отслеживания с настраиваемой выдачей. Требуется платная учётная запись.",
    "searchEnginesQwant": "Европейская поисковая система на базе результатов Bing.",
    "searchEnginesEcosia": "Направляет часть рекламного дохода на экологические проекты. Использует результаты Bing и Google.",
    "searchEnginesBing": "Популярный поиск Microsoft с персонализацией результатов и рекламы.",
    "searchEnginesGoogle": "Популярный поиск Google с персонализацией результатов и рекламы.",
    "defaultBrowserTitle": "Сделать Focus Browser основным?",
    "defaultBrowserSubtitle": "Тогда ссылки из других приложений будут открываться в Focus Browser. Выбор можно изменить в Windows.",
    "defaultBrowserYes": "Да, сделать основным",
    "defaultBrowserNo": "Не сейчас",
    "defaultBrowserYesDesc": "Открывать веб-ссылки в Focus Browser.",
    "defaultBrowserNoDesc": "Оставить текущий браузер основным.",
    "dataImportTitle": "Перенесите данные из другого браузера",
    "dataImportSubtitle": "Выберите профиль или импортируйте всё из Google Chrome одним нажатием.",
    "dataImportSubtitleNoChrome": "Выберите найденный браузер и данные, которые хотите перенести.",
    "dataImportBookmarks": "Закладки",
    "dataImportHistory": "История",
    "dataImportExtensions": "Расширения",
    "dataImportPasswords": "Пароли",
    "dataImportAutofill": "Автозаполнение",
    "dataImportSearchEngine": "Поисковая система",
    "dataImportLoading": "Ищем установленные браузеры…",
    "dataImportNone": "Профили для импорта не найдены. Можно продолжить без импорта.",
    "dataImportLoadError": "Не удалось получить список браузеров. Можно продолжить без импорта.",
    "dataImportImported": "Уже импортировано",
    "dataImportDefaultProfile": "Основной профиль",
    "dataImportChromeQuickTitle": "Импортировать всё из Google Chrome",
    "dataImportChromeQuickDesc": "Закладки, история, пароли, автозаполнение, поисковая система и расширения.",
    "dataImportChromeQuickButton": "Импортировать",
    "dataImportChromeQuickWorking": "Импортируем…",
    "dataImportChromeQuickDone": "Готово",
    "dataImportChromeQuickFailed": "Не удалось импортировать данные. Попробуйте ещё раз или выберите профиль ниже.",
    "dataImportChromeQuickRetry": "Повторить",
    "passwordTitle": "Менеджер паролей Focus",
    "passwordSubtitle": "Встроен в браузер и включён по умолчанию. Ничего дополнительно устанавливать не нужно.",
    "passwordLocalTitle": "Защищённое локальное хранение",
    "passwordLocalDesc": "Пароли шифруются средствами Windows и хранятся в вашем профиле Focus Browser.",
    "passwordFillTitle": "Автозаполнение и генерация",
    "passwordFillDesc": "Focus Browser сохраняет, подставляет и создаёт надёжные пароли прямо на сайтах.",
    "passwordPasskeysTitle": "Пароли и ключи доступа",
    "passwordPasskeysDesc": "Управляйте сохранёнными данными для входа и поддерживаемыми ключами доступа в одном месте.",
    "passwordOpenManager": "Открыть менеджер",
    "passwordOpenImport": "Импортировать пароли",
    "passwordNote": "Пароли из Chrome также можно перенести на предыдущем шаге импорта данных.",
    "passwordImportGuide": "Импорт",
    "passwordSetupGuide": "Настройка",
    "passwordPrivacy": "Конфиденциальность",
    "passwordInstall": "Установить",
    "passwordInstalled": "Установлено",
    "passwordError": "Ошибка:",
    "passwordManagersProtonPass": "Менеджер паролей Proton с открытым исходным кодом и бесплатным тарифом.",
    "passwordManagersBitwarden": "Популярный менеджер паролей с открытым исходным кодом, бесплатным тарифом и возможностью самостоятельного размещения.",
    "passwordManagersOnePassword": "Платный менеджер паролей с закрытым исходным кодом.",
    "passwordManagersDashlane": "Платный менеджер паролей с закрытым исходным кодом и хранением данных в Европе.",
    "passwordManagersIcloudPasswords": "Бесплатный менеджер паролей Apple. На Windows может требовать повторный вход после перезапуска браузера.",
    "passwordManagersKeePassXc": "Локальный бесплатный менеджер паролей с открытым исходным кодом для опытных пользователей.",}) : {};
const getString = (key: StringKey): string => {
    if (import.meta.env.DEV) {
        return (DEV_STRINGS as Record<StringKey, string>)[key];
    }

    const string = (loadTimeData ?? globalThis.loadTimeData)?.getString(key);
    if (!string) {
        console.error(`Could not get string for ${key}`);
        return `¡${key}!`;
    }

    return string;
};

export const s = {
    page: {
        get title() { return getString('pageTitle'); },
    },
    setup: {
        get caption() { return getString('setupCaption'); },
        get stepsAria() { return getString('setupStepsAria'); },
        get note() { return getString('setupNote'); },
        get stepFocus() { return getString('setupStepFocus'); },
        get stepAppearance() { return getString('setupStepAppearance'); },
        get stepSearch() { return getString('setupStepSearch'); },
        get stepImport() { return getString('setupStepImport'); },
        get stepPasswords() { return getString('setupStepPasswords'); },
        get stepDefault() { return getString('setupStepDefault'); },
        get stepShortcuts() { return getString('setupStepShortcuts'); },
    },
    button: {
        get useDefaults() { return getString('buttonUseDefaults'); },
        get configure() { return getString('buttonConfigure'); },
        get next() { return getString('buttonNext'); },
        get back() { return getString('buttonBack'); },
        get letsGo() { return getString('buttonLetsGo'); },
        get skip() { return getString('buttonSkip'); },
        get start() { return getString('buttonStart'); },
    },
    navigation: {
        get error() { return getString('navigationError'); },
    },
    partner: {
        get title() { return getString('partnerTitle'); },
        get tooltip() { return getString('partnerTooltip'); },
    },
    welcome: {
        get greeting() { return getString('welcomeGreeting'); },
        get body() { return getString('welcomeBody'); },
        get eyebrow() { return getString('welcomeEyebrow'); },
        get featuresLabel() { return getString('welcomeFeaturesLabel'); },
        get featureQuiet() { return getString('welcomeFeatureQuiet'); },
        get featureClean() { return getString('welcomeFeatureClean'); },
        get featureIntent() { return getString('welcomeFeatureIntent'); },
        get termsNote() { return getString('welcomeTermsNote'); },
        get termsPrivacy() { return getString('welcomeTermsPrivacy'); },
        get termsAnd() { return getString('welcomeTermsAnd'); },
        get termsUse() { return getString('welcomeTermsUse'); },
        get footer() { return getString('welcomeFooter'); },
    },
    focus: {
        get title() { return getString('focusTitle'); },
        get subtitle() { return getString('focusSubtitle'); },
        get quietTitle() { return getString('focusQuietTitle'); },
        get quietDesc() { return getString('focusQuietDesc'); },
        get minimalTitle() { return getString('focusMinimalTitle'); },
        get minimalDesc() { return getString('focusMinimalDesc'); },
        get motionTitle() { return getString('focusMotionTitle'); },
        get motionDesc() { return getString('focusMotionDesc'); },
        get note() { return getString('focusNote'); },
    },
    appearance: {
        get title() { return getString('appearanceTitle'); },
        get subtitle() { return getString('appearanceSubtitle'); },
        get barTitle() { return getString('appearanceBarTitle'); },
        get barFull() { return getString('appearanceBarFull'); },
        get barFullDesc() { return getString('appearanceBarFullDesc'); },
        get barCentered() { return getString('appearanceBarCentered'); },
        get barCenteredDesc() { return getString('appearanceBarCenteredDesc'); },
        get barMinimal() { return getString('appearanceBarMinimal'); },
        get barMinimalDesc() { return getString('appearanceBarMinimalDesc'); },
        get note() { return getString('appearanceNote'); },
    },
    shortcuts: {
        get title() { return getString('shortcutsTitle'); },
        get subtitle() { return getString('shortcutsSubtitle'); },
        get social() { return getString('shortcutsSocial'); },
        get coding() { return getString('shortcutsCoding'); },
        get ai() { return getString('shortcutsAi'); },
        get productivity() { return getString('shortcutsProductivity'); },
        get empty() { return getString('shortcutsEmpty'); },
        get selected() { return getString('shortcutsSelected'); },
        get limit() { return getString('shortcutsLimit'); },
    },
    finish: {
        get title() { return getString('finishTitle'); },
        get body() { return getString('finishBody'); },
    },
    search: {
        get title() { return getString('searchTitle'); },
        get subtitle() { return getString('searchSubtitle'); },
        get loading() { return getString('searchLoading'); },
        get none() { return getString('searchNone'); },
        get error() { return getString('searchError'); },
    },
    searchCategories: {
        get private() { return getString('searchCategoriesPrivate'); },
        get small() { return getString('searchCategoriesSmall'); },
        get mainstream() { return getString('searchCategoriesMainstream'); },
        get custom() { return getString('searchCategoriesCustom'); },
    },
    searchEngines: {
        get duckduckgo() { return getString('searchEnginesDuckduckgo'); },
        get kagi() { return getString('searchEnginesKagi'); },
        get qwant() { return getString('searchEnginesQwant'); },
        get ecosia() { return getString('searchEnginesEcosia'); },
        get bing() { return getString('searchEnginesBing'); },
        get google() { return getString('searchEnginesGoogle'); },
    },
    defaultBrowser: {
        get title() { return getString('defaultBrowserTitle'); },
        get subtitle() { return getString('defaultBrowserSubtitle'); },
        get yes() { return getString('defaultBrowserYes'); },
        get no() { return getString('defaultBrowserNo'); },
        get yesDesc() { return getString('defaultBrowserYesDesc'); },
        get noDesc() { return getString('defaultBrowserNoDesc'); },
    },
    dataImport: {
        get title() { return getString('dataImportTitle'); },
        get subtitle() { return getString('dataImportSubtitle'); },
        get subtitleNoChrome() { return getString('dataImportSubtitleNoChrome'); },
        get bookmarks() { return getString('dataImportBookmarks'); },
        get history() { return getString('dataImportHistory'); },
        get extensions() { return getString('dataImportExtensions'); },
        get passwords() { return getString('dataImportPasswords'); },
        get autofill() { return getString('dataImportAutofill'); },
        get searchEngine() { return getString('dataImportSearchEngine'); },
        get loading() { return getString('dataImportLoading'); },
        get none() { return getString('dataImportNone'); },
        get loadError() { return getString('dataImportLoadError'); },
        get imported() { return getString('dataImportImported'); },
        get defaultProfile() { return getString('dataImportDefaultProfile'); },
        get chromeQuickTitle() { return getString('dataImportChromeQuickTitle'); },
        get chromeQuickDesc() { return getString('dataImportChromeQuickDesc'); },
        get chromeQuickButton() { return getString('dataImportChromeQuickButton'); },
        get chromeQuickWorking() { return getString('dataImportChromeQuickWorking'); },
        get chromeQuickDone() { return getString('dataImportChromeQuickDone'); },
        get chromeQuickFailed() { return getString('dataImportChromeQuickFailed'); },
        get chromeQuickRetry() { return getString('dataImportChromeQuickRetry'); },
    },
    password: {
        get title() { return getString('passwordTitle'); },
        get subtitle() { return getString('passwordSubtitle'); },
        get localTitle() { return getString('passwordLocalTitle'); },
        get localDesc() { return getString('passwordLocalDesc'); },
        get fillTitle() { return getString('passwordFillTitle'); },
        get fillDesc() { return getString('passwordFillDesc'); },
        get passkeysTitle() { return getString('passwordPasskeysTitle'); },
        get passkeysDesc() { return getString('passwordPasskeysDesc'); },
        get openManager() { return getString('passwordOpenManager'); },
        get openImport() { return getString('passwordOpenImport'); },
        get note() { return getString('passwordNote'); },
        get importGuide() { return getString('passwordImportGuide'); },
        get setupGuide() { return getString('passwordSetupGuide'); },
        get privacy() { return getString('passwordPrivacy'); },
        get install() { return getString('passwordInstall'); },
        get installed() { return getString('passwordInstalled'); },
        get error() { return getString('passwordError'); },
    },
    passwordManagers: {
        get protonPass() { return getString('passwordManagersProtonPass'); },
        get bitwarden() { return getString('passwordManagersBitwarden'); },
        get onePassword() { return getString('passwordManagersOnePassword'); },
        get dashlane() { return getString('passwordManagersDashlane'); },
        get icloudPasswords() { return getString('passwordManagersIcloudPasswords'); },
        get keePassXc() { return getString('passwordManagersKeePassXc'); },
    },
} as const;
